# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarNumberTF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarNumberTF
  pod 'Masonry'
  pod 'CarNumberTF'

  target 'CarNumberTFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarNumberTFUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
